[package]
name = "day2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_tools = { version = "0.1.0", path = "../advent_tools" }
dialoguer = "0.11.0"
